<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="2" hostname="vitor-ub" name="pytest" skipped="0" tests="7" time="6.785" timestamp="2020-05-21T17:30:51.652766"><testcase classname="test_submit" file="test_submit.py" line="3" name="test_q1" time="0.001"><failure message="TypeError: &apos;numpy.float64&apos; object is not callable">E   TypeError: &apos;numpy.float64&apos; object is not callable</failure></testcase><testcase classname="test_submit" file="test_submit.py" line="11" name="test_q2" time="0.001"></testcase><testcase classname="test_submit" file="test_submit.py" line="16" name="test_q3" time="0.001"><failure message="TypeError: &apos;numpy.float64&apos; object is not callable">E   TypeError: &apos;numpy.float64&apos; object is not callable</failure></testcase><testcase classname="test_submit" file="test_submit.py" line="21" name="test_q4" time="0.001"></testcase><testcase classname="test_submit" file="test_submit.py" line="26" name="test_q5" time="0.000"></testcase><testcase classname="test_submit" file="test_submit.py" line="34" name="test_q6" time="0.001"></testcase><testcase classname="test_submit" file="test_submit.py" line="39" name="test_q7" time="0.001"></testcase></testsuite></testsuites>